### ISSUE TITLE
Accessing the CAMP HDF5 data

### ISSUE THREAD

**Issue by ml-evs** [materials-data-facility/publishing-battery-data#1]
Hi, just saw the announcement of this dataset on LinkedIn and would love to get my hands on it! Will the dataset be archived anywhere persistent with DOI, simple download link and license info, or is it provided on a more ad *hoc* basis?

I went through the process of making an account on globus (which seemed strange) but I seem to only be able to download one file at a time (and couldn't see the license).

Are the files meant to appear in the `hdf5` folder of this repo too?

Cheers!

**Comment by WardLT** [comment]
Hey Matt, Thanks for the questions! I'm going to add some information to this repo to help answer them, but wanted to reply directly.

> Will the dataset be archived anywhere persistent with DOI, or is it provided on a more ad hoc basis?

The MDF version is the persistent, archival copy. 

>simple download link 

We just added a "full_data.zip" that will download the full data over HTTPS.

The usual route for getting all the data is to transfer it from MDF to another system using [Globus Transfer](https://docs.globus.org/how-to/get-started/), but this is not apparent from the landing page for the data.

> and license info

 I missed adding the "CC-BY" license to the data. It should be up soon.
 
 > the process of making an account on globus (which seemed strange)
 
By "making," do you mean registering an existing account (e.g., your university creds) with Globus? You should also be able to download via HTTPS anonymously. 

> Are the files meant to appear in the hdf5 folder of this repo too?

No, they are larger than I prefer to use with GitHub (~750MB in total)

**Comment by ml-evs** [comment]
Hey Logan (sorry didn't make the connection between this and battery-data-toolkit in my head!) Thanks for the answers! 

I can now see the full data in globus and am able to download it all in one go, thanks!

> The usual route for getting all the data is to transfer it from MDF to another system using [Globus Transfer](https://docs.globus.org/how-to/get-started/), but this is not apparent from the landing page for the data.

Right, sorry, this is my first time trying to use globus myself. I don't think I have any institutional access to alternative globus endpoints, so I guess I would need to set up "Globus Connect Personal" to bring the data to my local machine (no longer necessary with this `full_data.zip` link).

> By "making," do you mean registering an existing account (e.g., your university creds) with Globus? You should also be able to download via HTTPS anonymously.

This doesn't seem to be the case, when I follow the link for "Get the data" on [this page](https://acdc.alcf.anl.gov/mdf/detail/camp_2023_v3.5/), I am taken to a Globus sign up page where I had to either make a GlobusID account or login via ORCID (I think I must have had an old account as ORCID sign-up/sign-in worked without any additional prompting).

**Comment by WardLT** [comment]
> when I follow the link for "Get the data" on [this page](https://acdc.alcf.anl.gov/mdf/detail/camp_2023_v3.5/)

You're absolutely right. I missed that point (was already logged in to Globus).

The README for this project now points to a direct download link which bypasses that authentication, and information on how to use Globus.

I'm adding "quick download links" and "how to use Globus links" to our to-do list for the Materials Data Facility. We're planning an overhaul of these dataset landing pages in the next few months.

**Comment by ml-evs** [comment]
Wonderful, thanks Logan! Feel free to close this as you please.
